name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t fabisdocker/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true fabisdocker/react-test-up npm test

      - run: docker build -t fabisdocker/multi-client-up ./client -f ./client/Dockerfile.dev
      - run: docker build -t fabisdocker/multi-nginx-up ./nginx -f ./nginx/Dockerfile.dev
      - run: docker build -t fabisdocker/multi-server-up ./server -f ./server/Dockerfile.dev
      - run: docker build -t fabisdocker/multi-worker-up ./worker -f ./worker/Dockerfile.dev

      - run: docker push fabisdocker/multi-client-up
      - run: docker push fabisdocker/multi-nginx-up
      - run: docker push fabisdocker/multi-server-up
      - run: docker push fabisdocker/multi-worker-up